const data = [
  {
    id: 1,
    name: "Agra",
    info: "Agra is a historic city in northern India, globally renowned for the iconic Taj Mahal, a monumental 17th-century white marble mausoleum built by Mughal Emperor Shah Jahan. The city also features spectacular architectural wonders like the massive Agra Fort and the ancient capital of Fatehpur Sikri.",
    image: "https://images.unsplash.com/photo-1564507592333-c60657eea523?q=80&w=600",
    price: "35,758",
  },
  {
    id: 2,
    name: "Jaipur",
    info: "Jaipur is the majestic capital city of Rajasthan, widely celebrated for its rich royal heritage, formidable forts, and distinct pink-colored architecture. Key historical landmarks include the stunning Hawa Mahal, the sprawling Amber Fort, and the intricate astronomical instruments of Jantar Mantar.",
    image: "https://images.unsplash.com/photo-1477587458883-471a5ed94245?q=80&w=600",
    price: "82,560",
  },
  {
    id: 3,
    name: "Goa",
    info: "Goa is a vibrant coastal state on India's southwestern shores, famous worldwide for its pristine sandy beaches, lively nightlife, and water sports. The region beautifully blends Indian and Portuguese cultures, visible in its 17th-century heritage churches, historic forts, and spicy cuisine.",
    image: "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?q=80&w=600",
    price: "29,695",
  },
  {
    id: 4,
    name: "Varanasi",
    info: "Varanasi is a sacred city in Uttar Pradesh resting on the banks of the holy Ganges River, universally regarded as the spiritual capital of India. It attracts millions of pilgrims to its ancient ghats for ritual bathing, mystical evening Ganga Aarti ceremonies, and deep spiritual exploration.",
    image: "https://images.unsplash.com/photo-1561361531-99522c3a1211?q=80&w=600",
    price: "24,500",
  },
  {
    id: 5,
    name: "Mumbai",
    info: "Mumbai, formerly known as Bombay, is India's sprawling financial capital and busiest metropolis. It serves as the epicenter of the Bollywood film industry, showcasing grand colonial architecture like the Gateway of India alongside scenic coastal spots like the iconic Marine Drive promenade.",
    image: "https://images.unsplash.com/photo-1496372412473-e8548ffd82bc?q=80&w=600",
    price: "68,400",
  },
  {
    id: 6,
    name: "Delhi",
    info: "Delhi, India’s massive capital territory, is an energetic urban hub where centuries of profound history seamlessly merge with fast-paced modern life. The bustling city features majestic historic landmarks like the Red Fort, Qutub Minar, Humayun's Tomb, and the political center of New Delhi.",
    image: "https://images.unsplash.com/photo-1587474260584-136574528ed5?q=80&w=600",
    price: "42,900",
  },
  {
    id: 7,
    name: "Udaipur",
    info: "Famously known as the 'City of Lakes', Udaipur is a romantic destination in Rajasthan nestled around the tranquil waters of Lake Pichola. The scenic city is celebrated for its breathtaking marble palaces, historic temples, beautiful royal courtyards, and spectacular sunset views over the hills.",
    image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?q=80&w=600",
    price: "55,200",
  },
  {
    id: 8,
    name: "Kochi",
    info: "Kochi is a lively coastal port city in Kerala defined by its unique multicultural identity. It features a fascinating blend of old-world charm and modern development, showcasing historic Chinese fishing nets, busy spice markets, ancient synagogues, and centuries-old European architecture.",
    image: "https://images.unsplash.com/photo-1589308078059-be1415eab4c3?q=80&w=600",
    price: "38,150",
  },
  {
    id: 9,
    name: "Bengaluru",
    info: "Bengaluru, recognized as the Silicon Valley of India, is a thriving technological mega-city. It is widely appreciated for its beautiful, sprawling public parks, lush botanical gardens, remarkably pleasant year-round climate, and an energetic, trendy corporate and cafe culture lifestyle.",
    image: "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?q=80&w=600",
    price: "47,300",
  },
  {
    id: 10,
    name: "Kolkata",
    info: "Kolkata, proudly standing as the cultural capital of India, is an artistic hub rich in literary tradition. Located along the Hooghly River, it is famous for its majestic grand British colonial architecture, historical hand-pulled rickshaws, artistic festivals, and delicious traditional sweets.",
    image: "https://images.unsplash.com/photo-1558431382-27e303142255?q=80&w=600",
    price: "31,800",
  },
  {
    id: 11,
    name: "Amritsar",
    info: "Amritsar is the deeply spiritual and cultural center of the Sikh faith, located in Punjab. It houses the magnificent Harmandir Sahib, globally known as the Golden Temple, which offers unmatched serenity, alongside moving historic sites like Jallianwala Bagh and the Wagah Border ceremony.",
    image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?q=80&w=600",
    price: "22,450",
  },
  {
    id: 12,
    name: "Manali",
    info: "Manali is a breathtaking high-altitude Himalayan resort town nestled in Himachal Pradesh. It is highly popular among adventure enthusiasts and backpackers for its thrilling activities like paragliding, skiing, trekking, and exploring scenic, snow-capped valleys and rapid mountain rivers.",
    image: "https://images.unsplash.com/photo-1605649487212-47bdab064df7?q=80&w=600",
    price: "41,200",
  },
  {
    id: 13,
    name: "Shimla",
    info: "Shimla, the legendary former summer capital of British India, is a picturesque hill station tucked away in the Himalayas. It is celebrated for its well-preserved Victorian architecture, the historic narrow-gauge toy train railway line, and beautiful, bustling pedestrian shopping streets.",
    image: "https://images.unsplash.com/photo-1562670224-4f05167098e0?q=80&w=600",
    price: "36,800",
  },
  {
    id: 14,
    name: "Hyderabad",
    info: "Hyderabad is a dynamic technology hub boasting a legendary history. It offers visitors a rich blend of monumental Islamic heritage, featuring iconic historic structures like the Charminar and Golconda Fort, perfectly paired with its globally famous, authentic Nizami cuisine and biryanis.",
    image: "https://images.unsplash.com/photo-1605007493699-af65834f8a00?q=80&w=600",
    price: "45,600",
  },
  {
    id: 15,
    name: "Jaisalmer",
    info: "Known beautifully as 'The Golden City', Jaisalmer rests proudly in the heart of Rajasthan's Thar Desert. The city is distinguished by its massive, shimmering yellow sandstone fort that rises over the horizon, extensive scenic sand dunes, camel safaris, and intricately carved historic havelis.",
    image: "https://images.unsplash.com/photo-1605538032432-a9f0c8d9baac?q=80&w=600",
    price: "51,900",
  },
  {
    id: 16,
    name: "Munnar",
    info: "Munnar is a scenic and tranquil hill station located in Kerala, nestled neatly within the Western Ghats mountain range. The region is widely famous for its vast, rolling emerald-green tea plantations, misty mountain valleys, refreshing waterfalls, exotic wildlife, and cool hiking trails.",
    image: "https://images.unsplash.com/photo-1593693397690-362cb9666fc2?q=80&w=600",
    price: "28,700",
  },
  {
    id: 17,
    name: "Chennai",
    info: "Situated on the scenic coast of the Bay of Bengal, Chennai is a powerful cultural, educational, and economic hub in South India. The city is deeply celebrated for its ancient Dravidian temples, rich musical traditions, classical Bharatanatyam dance heritage, and the massive Marina Beach.",
    image: "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?q=80&w=600",
    price: "34,200",
  },
  {
    id: 18,
    name: "Ooty",
    info: "Ooty is a peaceful and highly popular resort town nestled deep within the scenic Nilgiri Hills of Tamil Nadu. It is widely celebrated by travelers for its vast, fragrant tea gardens, calm lakes, stunning botanical varieties, pleasant mountain weather, and colonial-era heritage buildings.",
    image: "https://images.unsplash.com/photo-1598964344754-00109968a356?q=80&w=600",
    price: "33,500",
  },
  {
    id: 19,
    name: "Darjeeling",
    info: "Darjeeling is situated in the majestic Himalayan foothills of West Bengal, world-renowned for producing exceptionally premium black tea. The iconic hill town offers breathtaking panoramic views of Mount Kanchenjunga, alongside a charming historic UNESCO World Heritage mountain railway.",
    image: "https://images.unsplash.com/photo-1542856391-010fb87dcfed?q=80&w=600",
    price: "39,100",
  },
  {
    id: 20,
    name: "Puducherry",
    info: "Puducherry is a peaceful coastal union territory that still beautifully preserves its unique French colonial history. The charming town offers travelers distinct tree-lined avenues, bright mustard-colored historical colonial villas, tranquil sandy beaches, and cozy, authentic French cafes.",
    image: "https://images.unsplash.com/photo-1586790175850-25e243dae43e?q=80&w=600",
    price: "27,400",
  }
];

export default data;